//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> Placeofissue { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CopyofPassport { get; set; }
        public string ResidenceNumber { get; set; }
        public string UnifiedNumber { get; set; }
        public Nullable<System.DateTime> DateofResidence { get; set; }
        public Nullable<System.DateTime> ExpirationofResidence { get; set; }
        public string ResidenceCopy { get; set; }
        public string LaborCardNumber { get; set; }
        public Nullable<System.DateTime> LaborCardExpiryDate { get; set; }
        public string EmiratesIDNumber { get; set; }
        public Nullable<System.DateTime> EmiratedExpiryDate { get; set; }
        public string FrontFaceforEmiratesID { get; set; }
        public string BackfaceForEmiratesID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual RefDetails RefNationality { get; set; }
        public virtual RefDetails RefPlaceOfIssue { get; set; }
        public virtual RefDetails RefPosition { get; set; }
    }
}
