//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<decimal> AmountNo { get; set; }
        public string AmountText { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public string CheckNo { get; set; }
        public string BankName { get; set; }
        public string ExchangeOfficeName { get; set; }
        public string Note { get; set; }
    }
}
