//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransportEntities : DbContext
    {
        public TransportEntities()
            : base("name=TransportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bond> Bonds { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Custmers> Custmers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<RefDetails> RefDetails { get; set; }
        public virtual DbSet<RefHeader> RefHeaders { get; set; }
    }
}
