//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportSmart.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportSmart.Web.Resources.LanguageText", typeof(LanguageText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Phone Number.
        /// </summary>
        public static string AdditionalPhoneNumber {
            get {
                return ResourceManager.GetString("AdditionalPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Person.
        /// </summary>
        public static string AuthorizedPerson {
            get {
                return ResourceManager.GetString("AuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Type.
        /// </summary>
        public static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Back Side ID.
        /// </summary>
        public static string CopyBackSideID {
            get {
                return ResourceManager.GetString("CopyBackSideID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Front Side ID.
        /// </summary>
        public static string CopyFrontSideID {
            get {
                return ResourceManager.GetString("CopyFrontSideID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Of Residence.
        /// </summary>
        public static string CopyOfResidence {
            get {
                return ResourceManager.GetString("CopyOfResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer information.
        /// </summary>
        public static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers revealed.
        /// </summary>
        public static string CustomersRevealed {
            get {
                return ResourceManager.GetString("CustomersRevealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth Of The Employee.
        /// </summary>
        public static string DateOfBirthOfTheEmployee {
            get {
                return ResourceManager.GetString("DateOfBirthOfTheEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Issuance Of Residence.
        /// </summary>
        public static string DateOfIssuanceOfResidence {
            get {
                return ResourceManager.GetString("DateOfIssuanceOfResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string EmployeeNumber {
            get {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID And Labor Card Information.
        /// </summary>
        public static string IDAndLaborCardInformation {
            get {
                return ResourceManager.GetString("IDAndLaborCardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Card Expiry Date.
        /// </summary>
        public static string LaborCardExpiryDate {
            get {
                return ResourceManager.GetString("LaborCardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Card Number.
        /// </summary>
        public static string LaborCardNumber {
            get {
                return ResourceManager.GetString("LaborCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Password?.
        /// </summary>
        public static string LostPassword {
            get {
                return ResourceManager.GetString("LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Copy.
        /// </summary>
        public static string PassportCopy {
            get {
                return ResourceManager.GetString("PassportCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Employee Information.
        /// </summary>
        public static string PersonalEmployeeInformation {
            get {
                return ResourceManager.GetString("PersonalEmployeeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Of Issue.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence Expiry Date.
        /// </summary>
        public static string ResidenceExpiryDate {
            get {
                return ResourceManager.GetString("ResidenceExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residenct Information.
        /// </summary>
        public static string ResidenctInformation {
            get {
                return ResourceManager.GetString("ResidenctInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Number.
        /// </summary>
        public static string ResidencyNumber {
            get {
                return ResourceManager.GetString("ResidencyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE Identity Expiry Date.
        /// </summary>
        public static string UAEIdentityExpiryDate {
            get {
                return ResourceManager.GetString("UAEIdentityExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE ID Number.
        /// </summary>
        public static string UAEIDNumber {
            get {
                return ResourceManager.GetString("UAEIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Number.
        /// </summary>
        public static string UnifiedNumber {
            get {
                return ResourceManager.GetString("UnifiedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
